### PR TITLE
Fixes #154

### LINKED ISSUE #154: Arrow key navigation of bookmarks is broken
When focusing bookmarks outside of the viewport, it doesn't scroll to show them.
Relevant to #107.

### PR DESCRIPTION
**Pull request by Cybolic**
Fixes the keyboard navigation scrolling issue described in #154

### CODE REVIEW

File: src/modules/scroll-window.ts [hunk 1]
```diff
@@ -1,10 +1,16 @@
+import { headerHeight as headerHeightInPx } from '~/containers/search-controls';
+const headerHeight = parseInt(headerHeightInPx);
+
 export const scrollToTop: IO<void> = () => {
 	window.scrollTo(0, 0);
 };
 
-export const scrollToEl = (el: HTMLElement): IO<void> => (): void => {
-	const headerHeight = parseInt(window.getComputedStyle(document.body).getPropertyValue('--header-height'), 10);
+export const scrollToEl = (el: HTMLElement): void => {
```
Comment (samhh) [inline src/modules/scroll-window.ts:8]: Haven't been in the codebase for a little while but I'd like to retain the previous type signature which expressed impurity. Might be that as a result an extra function call needs adding wherever it's being called.

Otherwise thanks for your contribution, looking good for me locally. :smile:

**Review by samhh — CHANGES_REQUESTED** [review]

File: src/modules/scroll-window.ts (hunk 1 above)
Comment (Cybolic) [reply src/modules/scroll-window.ts]: Gotcha. I've committed a fix for that.

**Review by samhh — APPROVED** [review]
